## Random Numbers
#### Refer for nice doc https://www.w3schools.com/python/numpy_random.asp 

In [126]:
import numpy as np 
from numpy import random as rd

import random as pyrd  #inbuilt Python

In [103]:
xyz=np.array([23,45,12,34,11,21,31]) 
rd.shuffle(xyz)
xyz

array([34, 31, 23, 12, 45, 21, 11])

In [104]:
rd.permutation(xyz)#shuffle               Randomly permute a sequence, or return a permuted range.

array([31, 23, 45, 21, 34, 12, 11])

In [74]:
rd.choice([3, 5, 7, 9]) #from given array!

5

In [86]:
rd.choice([3, 5, 7, 9,10,1,2,0,20,99,11],size=(3,3))

array([[20,  5,  9],
       [11,  3,  0],
       [ 1,  3, 10]])

In [91]:
#'p' defines probability for each mapped array element ==1

rd.choice([3, 5, 7, 9], p=[0.1, 0.2, 0.5, 0.2], size=(20)) 

array([9, 7, 5, 7, 9, 3, 7, 7, 7, 7, 3, 7, 7, 7, 7, 5, 7, 9, 5, 9])

In [95]:
rd.choice([3, 5, 7, 9], p=[0.4, 0.4, 0.1, 0.1], size=(4, 5))

array([[3, 5, 3, 5, 3],
       [3, 9, 3, 5, 3],
       [7, 3, 5, 9, 3],
       [5, 3, 7, 3, 3]])

In [77]:
rd.random() #random using np: cumsum, cumprod, where (logical)

0.8983749525383176

In [32]:
rd.random(2)

array([0.57554016, 0.28256802])

In [44]:
rf = np.random.rand(10) #10 Float numbers 0 to 1
rf

array([0.20261884, 0.45985434, 0.53239162, 0.55451209, 0.04905148,
       0.66622852, 0.41761032, 0.93395097, 0.58070692, 0.40424903])

In [19]:
rf1 = np.random.rand(2,4) 
rf1

array([[0.6020488 , 0.45409753, 0.67647532, 0.11784516],
       [0.61234887, 0.43233578, 0.24055506, 0.37635879]])

In [21]:
rf2 = np.random.randn(3,2,4) #3 rows with 2,4
rf2

array([[[ 0.87356627,  0.81350082,  0.22798055, -1.24807727],
        [-0.82270332,  0.07395308, -0.64506755, -0.34628896]],

       [[-1.6469085 , -0.46161594,  0.23830313,  0.37588677],
        [ 0.35560518, -1.04261895, -1.34578148, -0.07448543]],

       [[ 0.94825061, -0.03372961,  0.18590733, -0.26098223],
        [ 1.08896897, -0.02546349, -0.44293316, -0.14525588]]])

In [43]:
rf3 = np.random.randn(51) 
rf3

array([-0.60968241, -0.67307763,  0.95737372, -0.6280861 ,  0.89601544,
       -1.30272062, -0.01248933,  0.58466306,  0.15470181,  0.17755898,
       -0.29212728,  0.84260681, -0.12700645, -0.02915741, -0.79361235,
        1.15272392,  0.48709451, -1.38486166,  0.02871019,  2.12665348,
       -0.09127179,  0.32622073,  0.45869801, -1.23525427, -1.17311435,
        0.99568525,  0.05520719,  0.55644302,  1.65014107,  0.12370841,
        0.36562756,  1.06662457,  0.22390413,  0.71012116, -0.39899861,
        0.38615226,  0.69985758,  0.72593753, -0.22434551,  1.80307305,
        1.22367777, -2.5879093 , -0.20490921,  0.42963384,  0.23735062,
       -0.11959976,  0.32957462, -0.04539697,  0.23073805,  0.03194771,
       -0.48022431])

In [45]:
r1 = np.random.randint(10) #Single Int 0 to 10
r1

1

In [60]:
r2 = np.random.randint(10,size=(1,15)) #Single Int 0 to 10
r2

array([[7, 0, 3, 2, 1, 2, 3, 4, 8, 0, 5, 5, 1, 9, 4]])

In [62]:
np.count_nonzero(r2) #Counts the number of non-zero elements in the input array

13

In [61]:
np.nonzero(r2) #Return the indices of the elements that are non-zero.

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([ 0,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14], dtype=int64))

In [47]:
r3 = np.random.randint(99,size=(2,6)) #random int from 0-99 in asked size -- shape!
r3

array([[97, 80,  6, 25, 37, 53],
       [17, 36, 84, 31, 12, 79]])

In [51]:
r4=np.random.randint(1,80,20)#.reshape((5,4))
r4

array([38, 60, 28, 19, 27, 29, 60, 40, 73, 36, 66, 31, 31, 22, 65, 60, 63,
       51, 28, 42])

In [57]:
r5=np.random.randint(0,80,20).reshape((5,4))
r5

array([[76, 54,  2,  7],
       [22, 65, 69, 53],
       [24, 17, 74, 22],
       [37, 61,  6, 34],
       [71, 58, 15, 27]])

In [64]:
r4.max()

73

In [63]:
r5.min()

2

In [122]:
#Random Float Values from Given Input Range!

np.random.uniform(1,10)

4.840970366889492

In [123]:
np.random.uniform(1,10,size=(2,5))

array([[3.99330515, 6.97150647, 8.72323268, 7.63815274, 3.85257047],
       [3.09027339, 1.41937047, 8.77748077, 8.12726029, 3.14551043]])

Normal Distribution (Gaussian Distribution)

In [66]:
nd = np.random.normal(10)#(3,5)) 
nd

9.461766014216881

In [67]:
nd1 = np.random.normal((1,9))
nd1

array([0.32887661, 9.20768708])

In [70]:
nd2 = np.random.normal(1,99,30)
nd2

array([   1.57403769,  -42.72044379,  190.8925084 , -133.13167547,
         78.30591053,  -93.08360838, -120.65398312,  239.11690039,
         26.93209431,  113.43951514,  -91.29783147,  -72.99225445,
        -59.2122297 ,  -36.56710096,  -92.92235448,  194.1141704 ,
        -74.54924471,   36.00554992,   95.72350692,   12.89103694,
         -9.92425995,   -7.40560701,  135.96438676, -119.35664913,
        160.65053077,    7.75343184, -176.25698707,   21.20987568,
        -22.26287329,  -21.6961153 ])

In [73]:
nd3 = np.random.normal(size=(2,4))
nd3

array([[-0.89418729, -1.45812625, -0.53352093, -0.0955831 ],
       [-1.42795512,  0.7883062 ,  1.98963046, -0.13599402]])

In [112]:
# Random normal distribution with mean=2, std=2.5 and size(x,y)

nd4 = rd.normal(loc=1, scale=2, size=(2, 3))
nd4

array([[ 3.75089071,  0.09825832, -0.6377877 ],
       [ 1.05939366,  0.76216427, -0.67322737]])

Binomial or Discrete Distribution!

In [117]:
# Binomial distribution with number_of_trial=2, probability_of_each_trial=2.5 and size(x,y)

rd.binomial(n=10, p=0.5, size=10)

array([5, 7, 2, 5, 4, 6, 5, 7, 3, 6])

In [119]:
rd.binomial(n=2, p=0.5, size=(2,4))

array([[2, 1, 1, 1],
       [2, 2, 1, 2]])