In [2]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [3]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([-0.49213553,  0.92998983,  0.56615307, -0.63497318, -0.48011805,
        0.60023712, -0.94971545,  0.14369211,  0.22818629, -0.48007272])

In [7]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-0.65024162,  0.94362788,  0.89619552,  1.18025264, -1.1472068 ,
       -0.84121893,  1.48331042, -0.19043447, -0.70659592, -0.19833202])

In [8]:
#Addition
np.add(A,B)

array([-1.14237715,  1.87361771,  1.46234859,  0.54527946, -1.62732485,
       -0.2409818 ,  0.53359497, -0.04674236, -0.47840963, -0.67840474])

In [9]:
#Finding max or min between two arrays
np.maximum(A,B)

array([-0.49213553,  0.94362788,  0.89619552,  1.18025264, -0.48011805,
        0.60023712,  1.48331042,  0.14369211,  0.22818629, -0.19833202])

In [11]:
np.minimum(A,B)

array([-0.65024162,  0.92998983,  0.56615307, -0.63497318, -1.1472068 ,
       -0.84121893, -0.94971545, -0.19043447, -0.70659592, -0.48007272])

In [12]:
np.random.randint(10)

2

#For full and extensive list of all universal functions
http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs

In [24]:
ran=np.random.randint(1,10,20).reshape((5,4))
ran

array([[4, 6, 9, 1],
       [5, 7, 9, 7],
       [5, 1, 6, 6],
       [9, 8, 8, 9],
       [7, 7, 7, 8]])

In [17]:
ran.max() #np.argmax()

9

In [18]:
ran.min() #np.argmin()

1

In [20]:
#dir(ran)

In [22]:
np.nonzero(ran) #Return the indices of the elements that are non-zero.

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19], dtype=int64),)

In [23]:
np.count_nonzero(ran) #Counts the number of non-zero elements in the input array

20

In [ ]:
#random using np.: cumsum, cumprod

In [ ]:
np.random.normal((3,5)) #np.random.normal((3,5,20))

In [ ]:
a = np.random.normal(size=(2,2))

In [ ]:
a.ravel() #One dim -> change