In [1]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
#Calcualting exponential (e^)
np.exp(arr)

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([ 0.65241981,  0.95666132,  0.16352424,  0.37234507,  0.50855163,
       -1.07329709, -0.56919638,  0.21422455, -0.04846319, -0.41031454])

In [6]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-1.12490369, -0.17461957,  2.13152167, -0.58259431,  0.38949821,
       -0.05302735,  0.40820781,  0.13299115, -0.45702765, -0.49964636])

In [7]:
#Addition
np.add(A,B)

array([-0.47248389,  0.78204176,  2.29504591, -0.21024923,  0.89804983,
       -1.12632444, -0.16098857,  0.34721571, -0.50549085, -0.9099609 ])

In [8]:
#Finding max or min between two arrays
np.maximum(A,B)

array([ 0.65241981,  0.95666132,  2.13152167,  0.37234507,  0.50855163,
       -0.05302735,  0.40820781,  0.21422455, -0.04846319, -0.41031454])

In [9]:
np.minimum(A,B)

array([-1.12490369, -0.17461957,  0.16352424, -0.58259431,  0.38949821,
       -1.07329709, -0.56919638,  0.13299115, -0.45702765, -0.49964636])

In [10]:
np.random.randint(10)

6

#For full and extensive list of all universal functions
http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs

In [11]:
ran=np.random.randint(1,10,20).reshape((5,4))
ran

array([[4, 2, 3, 5],
       [9, 6, 7, 1],
       [3, 9, 6, 6],
       [3, 6, 9, 2],
       [5, 6, 1, 8]])

In [12]:
ran.max() #np.argmax()

9

In [13]:
ran.min() #np.argmin()

1

In [14]:
#dir(ran)

In [15]:
np.nonzero(ran) #Return the indices of the elements that are non-zero.

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4],
       dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       dtype=int64))

In [16]:
np.count_nonzero(ran) #Counts the number of non-zero elements in the input array

20

In [17]:
#random using np.: cumsum, cumprod

In [18]:
np.random.normal((3,5)) #np.random.normal((3,5,20))

array([3.86569763, 4.94556962])

In [19]:
a = np.random.normal(size=(2,2))

In [20]:
a.ravel() #One dim -> change

array([-1.44339252,  0.02602608, -0.80629843,  1.17944979])