## Random Numbers
#### Refer for nice doc https://www.w3schools.com/python/numpy_random.asp 

In [34]:
import numpy as np 

from numpy import random as rd

#import random as pyrd  #inbuilt Python -> check (pip install random --user)

In [42]:
xyz=np.array([23,45,12,34,11,21,31]) 

rd.shuffle(xyz)  #shuffle: value randomize
xyz

array([31, 45, 21, 12, 23, 11, 34])

In [35]:
xyz=np.array([23,45,12,34,11,21,31]) 
xyz

array([23, 45, 12, 34, 11, 21, 31])

In [3]:
rd.permutation(xyz) #shuffle               Randomly permute a sequence, or return a permuted range.

array([45, 11, 31, 21, 23, 12, 34])

In [4]:
rd.choice([3, 5, 7, 9]) #Pick: from given array!

3

In [5]:
rd.choice([3, 5, 7, 9,10,1,2,0,20,99,11],size=(3,3))

array([[0, 3, 7],
       [2, 1, 7],
       [1, 7, 0]])

In [6]:
#'p' defines probability for each mapped array element ==1

rd.choice([3, 5, 7, 9], p=[0.3, 0.2, 0.3, 0.2], size=(20)) 

array([3, 7, 9, 7, 3, 3, 7, 5, 9, 5, 5, 3, 5, 3, 7, 5, 7, 9, 7, 7])

In [7]:
rd.choice([3, 5, 7, 9], p=[0.4, 0.4, 0.1, 0.1], size=(4, 5))

array([[3, 5, 3, 5, 3],
       [5, 5, 5, 5, 5],
       [5, 3, 5, 3, 9],
       [3, 7, 7, 5, 9]])

In [8]:
rd.random() #random using np: cumsum, cumprod, where (logical)

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.

0.10683360434675471

In [9]:
rd.random(3)

array([0.97760016, 0.42920666, 0.50373649])

In [10]:
rf = np.random.rand(10) #10 Float numbers 0 to 1
rf

array([0.3983319 , 0.47880162, 0.28097494, 0.23870068, 0.72807691,
       0.37951794, 0.17861271, 0.3195626 , 0.94145351, 0.99072939])

In [11]:
rf1 = np.random.rand(2,4) 
rf1

array([[0.17330359, 0.00192083, 0.3597525 , 0.84741883],
       [0.40111968, 0.53187583, 0.73418199, 0.12540007]])

In [12]:
rf2 = np.random.randn(3,2,4) #3 rows with 2,4   # -1 0 1
rf2 

array([[[-0.84735513,  1.15489255, -1.02406492,  0.19626866],
        [-0.79807126, -0.86332614,  0.4005937 , -1.54928507]],

       [[-0.16873566, -0.36777883,  0.38565377,  2.11832507],
        [ 0.16560311,  0.60078398,  0.99505723,  0.24664411]],

       [[-0.26733703, -1.40685552,  0.25662835, -0.06936258],
        [ 0.73167775,  0.94453638,  0.13602111,  0.81383752]]])

In [13]:
rf3 = np.random.randn(51) 
rf3

array([ 1.2296456 ,  2.76213865, -1.67150478,  1.31452911, -0.06503627,
       -0.23473387,  3.47305   , -1.93041337, -0.38589428, -0.05406956,
       -1.70309017,  0.64473973, -0.52284081,  1.52045232,  0.57327441,
        1.51103744, -0.58360869, -0.0747697 ,  1.14596722, -0.10655358,
        0.58456445, -1.68595285,  0.5301645 , -0.22135261,  0.62430312,
       -1.44435241, -1.22096458,  0.13770287, -0.38560561, -3.03920253,
       -0.92760783, -0.64680735,  0.73963555, -0.74379609, -0.05007727,
       -0.47474921, -0.7425876 , -1.56264329, -0.1536858 ,  1.04175061,
       -0.10036497, -2.04351322,  2.34119042,  0.42229604,  0.93820971,
       -0.52927925,  0.21978783,  1.27483574,  1.01822163,  0.87818064,
        0.77081605])

In [14]:
r1 = np.random.randint(10) #Single Int 0 to 10
r1

8

In [15]:
r2 = np.random.randint(10,size=(1,15)) #Single Int 0 to 10
r2

array([[5, 8, 4, 9, 1, 6, 6, 0, 4, 7, 3, 1, 6, 5, 7]])

In [16]:
np.count_nonzero(r2) #Counts the number of non-zero elements in the input array

14

In [17]:
np.nonzero(r2) #Return the indices of the elements that are non-zero.

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14],
       dtype=int64))

In [18]:
r3 = np.random.randint(99,size=(2,6)) #random int from 0-99 in asked size -- shape!
r3

array([[33, 78, 33, 27, 58, 17],
       [83, 17, 13, 90, 37, 23]])

In [19]:
r4=np.random.randint(1,80,50)#.reshape((5,4))   #np.random.randint(80,size=(1,20))
r4

array([14,  5, 30, 15, 19, 61,  6, 12, 11, 42, 64, 62,  3, 47, 54, 35,  1,
       35, 54, 42, 10, 70, 70, 56, 11, 56, 15, 21, 37, 57, 58,  5, 16,  6,
        7, 47, 65, 18, 63, 57, 40, 22, 45, 73, 65, 61, 61, 16, 20,  4])

In [20]:
r45 = r4.reshape((2,25))
r45

array([[14,  5, 30, 15, 19, 61,  6, 12, 11, 42, 64, 62,  3, 47, 54, 35,
         1, 35, 54, 42, 10, 70, 70, 56, 11],
       [56, 15, 21, 37, 57, 58,  5, 16,  6,  7, 47, 65, 18, 63, 57, 40,
        22, 45, 73, 65, 61, 61, 16, 20,  4]])

In [21]:
r5=np.random.randint(0,80,20).reshape((2,10))       #TASK: probability??
r5

array([[58, 22,  4, 78,  2, 61, 78,  2, 64, 17],
       [ 1,  0, 52, 58, 20, 62, 10,  2, 76, 73]])

In [22]:
r4.max()

73

In [23]:
r5.max()

78

In [24]:
r5.min()

0

In [25]:
#Random Float Values from Given Input Range!

np.random.uniform(1,10)

1.6159499581044294

In [26]:
np.random.uniform(1,10,size=(2,5))

array([[8.855618  , 9.10975647, 5.77019017, 9.14765842, 7.33549529],
       [4.53384605, 2.96858767, 3.94055101, 7.3547323 , 1.42487789]])

## Normal Distribution (Gaussian Distribution)

In [27]:
nd = np.random.normal(10)#(3,5)) 
nd

11.604955753284788

In [28]:
nd1 = np.random.normal((1,9))
nd1

array([1.6354475 , 7.66739139])

In [29]:
nd2 = np.random.normal(1,99,15)
nd2

array([  68.23977159,  177.0336149 ,  201.28390086,  163.27548672,
       -228.68375407,  -10.05409479,  -57.02935993,   20.3652977 ,
          1.97678668,   29.34228912,   32.05965077,  -58.46095459,
       -132.82637846,   92.45467379, -103.87573396])

In [30]:
nd3 = np.random.normal(size=(2,4))
nd3

array([[-0.29741152, -0.85767   , -0.28247163, -1.94067609],
       [-0.78110591, -0.84441558, -0.95276037,  1.10987012]])

In [31]:
# Random normal distribution with mean=2, std=2.5 and size(x,y)

nd4 = rd.normal(loc=1, scale=2, size=(2, 3))
nd4

array([[ 2.20839615,  2.7753362 ,  2.0108401 ],
       [ 1.78340912, -0.77061609,  2.51113744]])

#### from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns
sns.distplot(random.normal(size=1000), hist=False)
plt.show()

Binomial or Discrete Distribution!

In [32]:
# Binomial distribution with number_of_trial=2, probability_of_each_trial=2.5 and size(x,y)

rd.binomial(n=10, p=0.5, size=10)

array([5, 5, 8, 5, 3, 6, 7, 2, 6, 5])

In [33]:
rd.binomial(n=2, p=0.5, size=(2,4))

array([[1, 1, 2, 2],
       [1, 2, 2, 2]])