In [11]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [4]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [8]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [17]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([ 1.67337614,  0.313715  , -0.54322771, -0.62989299, -1.80379121,
       -2.14201895,  0.55044184, -0.30340582,  0.38182576,  1.61825713])

In [18]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-0.36856389,  0.88334254,  0.73189034,  0.39825998, -0.13333202,
       -0.04089832, -0.17904368, -0.31792306, -0.51818526,  0.17130282])

In [19]:
#Addition
np.add(A,B)

array([-0.26311799,  0.46621906,  0.77886172, -1.34775418,  0.84899094,
       -0.10713425,  1.12217039,  0.30454513, -0.17441401,  1.15341669])

In [20]:
#Finding max or min between two arrays
np.maximum(A,B)

array([ 0.10544591,  0.88334254,  0.73189034,  0.39825998,  0.98232296,
       -0.04089832,  1.30121407,  0.62246819,  0.34377126,  0.98211387])

#For full and extensive list of all universal functions
http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs