In [1]:
import numpy as np
import sys
import os

In [2]:
#Create an array

arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
#Saving array on disk in binary format (file extension .npy)

np.save('my_arrayaug',arr)

In [4]:
#Change arr
arr = np.arange(10)
arr1 = np.arange(1,50,3)

#Show
print(arr)
print(arr1)

print("Memory size of 'arr' = "+str(sys.getsizeof(arr))+ " bytes")
print("Memory size of 'arr1' = "+str(sys.getsizeof(arr1))+ " bytes")

[0 1 2 3 4 5 6 7 8 9]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
Memory size of 'arr' = 136 bytes
Memory size of 'arr1' = 164 bytes


In [5]:
#Lets see the original saved copy

np.load('my_arrayaug.npy')

array([0, 1, 2, 3, 4])

In [6]:
#Saving multiple arrays into a zip file

np.savez('two_arrays.npz',x=arr,y=arr1)

In [7]:
#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')

#Show
print(archive_array['x'])
print(archive_array['y'])

[0 1 2 3 4 5 6 7 8 9]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [8]:
#Now lets remove them from the memory
os.remove('my_arrayaug.npy')

In [9]:
#del archive_array
#os.remove('two_arrays.npz')
#os.rmdir("two_arrays.npz")

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'two_arrays.npz'

In [10]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [11]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr


array([[1., 2., 3.],
       [4., 5., 6.]])