In [1]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [8]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
type(arr)

numpy.ndarray

In [10]:
lst = list(range(0,11))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [22]:
lst1 = list(range(20,31))
lst1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [23]:
lst+lst1  #add: concat

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [25]:
max(lst1)

30

In [11]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [12]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [18]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)
A

array([-1.21864562,  2.34335063, -0.15440771, -0.65535331,  0.61853832,
        0.48138918,  0.80874746,  0.09786465,  0.36180405,  0.71155047])

In [17]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-0.93641999,  1.33738563, -0.85752851, -0.98231485,  1.01911593,
       -0.513707  , -0.76737629,  1.12841109,  0.12867836,  0.98713631])

In [20]:
print(type(A))
print(type(B))

#class(values)  ...  <object of ... #230428342348 # >

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [21]:
#Addition
np.add(A,B)

array([-2.15506561,  3.68073625, -1.01193622, -1.63766817,  1.63765424,
       -0.03231782,  0.04137117,  1.22627574,  0.4904824 ,  1.69868678])

In [24]:
#Finding max or min between two arrays
np.maximum(A,B)

array([-0.93641999,  2.34335063, -0.15440771, -0.65535331,  1.01911593,
        0.48138918,  0.80874746,  1.12841109,  0.36180405,  0.98713631])

In [26]:
np.minimum(A,B)

array([-1.21864562,  1.33738563, -0.85752851, -0.98231485,  0.61853832,
       -0.513707  , -0.76737629,  0.09786465,  0.12867836,  0.71155047])

In [36]:
np.random.randint(10)

5

#For full and extensive list of all universal functions
http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs

In [37]:
ran=np.random.randint(1,10,20).reshape((5,4))
ran

array([[6, 2, 3, 6],
       [5, 6, 8, 9],
       [6, 4, 2, 1],
       [7, 3, 8, 8],
       [7, 2, 8, 4]])

In [17]:
ran.max() #np.argmax()

9

In [18]:
ran.min() #np.argmin()

1

In [41]:
#dir(ran)

In [40]:
#np.nonzero(ran) #Return the indices of the elements that are non-zero.

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4],
       dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       dtype=int64))

In [23]:
#np.count_nonzero(ran) #Counts the number of non-zero elements in the input array

20

In [ ]:
#random using np.: cumsum, cumprod

In [42]:
np.random.normal((3,5)) #np.random.normal((3,5,20))

array([2.21354905, 6.15429954])

In [47]:
a = np.random.normal(size=(3,5))
a

array([[-0.53420304, -1.7086281 ,  1.15061808, -0.61786334, -1.64416013],
       [ 0.66164307, -1.27547095,  0.8168898 , -1.81267509,  0.60925599],
       [-0.82130612, -0.48685805,  0.46563156, -0.10208392, -0.13005975]])

In [48]:
a.ravel() #One dim -> change

array([-0.53420304, -1.7086281 ,  1.15061808, -0.61786334, -1.64416013,
        0.66164307, -1.27547095,  0.8168898 , -1.81267509,  0.60925599,
       -0.82130612, -0.48685805,  0.46563156, -0.10208392, -0.13005975])