# Numpy : numerical python

## Creating arrays : https://numpy.org/

In [1]:
import numpy as np

In [3]:
# Creating Numpy arrays
# Converting from a list
#Lets start with a list

my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

In [4]:
#Print out array
my_array1

array([1, 2, 3, 4])

In [4]:
print(my_array1)

[1 2 3 4]


In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
print(type(my_array1))
print(my_array1.shape) #total number of elements or columns!

<class 'numpy.ndarray'>
(4,)


In [7]:
#Print List
my_list1

[1, 2, 3, 4]

In [8]:
# Make another list
my_list2 = [11,22,33,44]

#Make a list of lists
my_lists = [my_list1,my_list2]

print(my_lists)

#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2

[[1, 2, 3, 4], [11, 22, 33, 44]]


array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
#Lets get the shape of the array
my_array2.shape

(2, 4)

In [10]:
#Find out the data type of the array
my_array2.dtype

dtype('int32')

In [11]:
#Making special case arrays

#Zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zArray = np.zeros((5,5),dtype=int) #(5,2)
zArray

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
#Ones
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
# NOTE: An empty array: Careful! 
np.empty(5)

array([4.94065646e-324, 4.94065646e-324, 0.00000000e+000, 0.00000000e+000,
       5.26520936e+170])

In [20]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#NOTE
np.empty([3,4], dtype=int) #don't use shape with []!

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
#Full: full fill!
np.full((5,3),[1,9,2]) #shape, [values,values]

array([[1, 9, 2],
       [1, 9, 2],
       [1, 9, 2],
       [1, 9, 2],
       [1, 9, 2]])

In [25]:
np.full((2,3),[1,9,14]) #my_array2

array([[ 1,  9, 14],
       [ 1,  9, 14]])

In [18]:
#diagonal array
np.eye(5) #5 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.eye(4,2) #rows,cols

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.identity(10) #n: n x n array!

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
#IMPORTANT!
np.diag(np.identity(4)) #pass -> array, return diagnol values of entered array

array([1., 1., 1., 1.])

In [27]:
# Using a range()
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
np.arange(1,50,2) #start stop and step

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [27]:
len(np.arange(1,50,2))

25

In [28]:
np.arange(1,50,2).reshape((5,5)) #Reshape original array into given shape(x,y)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [29]:
np.arange(0,30).reshape((3,10)) #Reshape original array into given shape(x,y)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [35]:
np.arange(0,30).reshape((3,10)).ndim

2

In [29]:
np.arange(0,30).reshape((15,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [32]:
np.arange(0,30).reshape((15,2)).ndim

2

In [30]:
np.arange(0,30).reshape((15,2)).T ##transpose! 

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]])

In [33]:
np.arange(0,30).reshape((15,2)).T.ndim

2

In [31]:
np.arange(0,30).ravel()  #ravel: dissolve shape to 1dim or 1 row

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
np.arange(0,30).ravel().ndim

1

### Explore 1

In [31]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [32]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a.dtype #dtype('int32')  Data type of values

dtype('int32')

In [34]:
a.shape #(10,) ??? Shapes

(10,)

In [35]:
a.ndim #1 Dimension!

1

In [36]:
z=np.zeros((3,6))
z

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
z.shape

(3, 6)

In [38]:
z.ndim

2

In [39]:
xyz3d = np.arange(1,60,2).reshape((5,2,3)) #5 individual rows: each containing arrays of shape (2,3)
xyz3d

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[13, 15, 17],
        [19, 21, 23]],

       [[25, 27, 29],
        [31, 33, 35]],

       [[37, 39, 41],
        [43, 45, 47]],

       [[49, 51, 53],
        [55, 57, 59]]])

In [40]:
xyz3d = np.arange(1,60,2).reshape((2,5,3))   #Task: array([3,9,15,21,27,33,39,35,51,57])
xyz3d

array([[[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17],
        [19, 21, 23],
        [25, 27, 29]],

       [[31, 33, 35],
        [37, 39, 41],
        [43, 45, 47],
        [49, 51, 53],
        [55, 57, 59]]])

In [41]:
xyz3d.shape

(2, 5, 3)

In [42]:
xyz3d.ndim

3

## Type (dtype, astype)

In [43]:
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [44]:
arr1.dtype

dtype('int32')

In [45]:
arr2=np.array([23,45,1,2,3,4,5,8,9,0],dtype=float)
arr2

array([23., 45.,  1.,  2.,  3.,  4.,  5.,  8.,  9.,  0.])

In [46]:
arr2.dtype

dtype('float64')

In [47]:
arr2.astype(arr1.dtype) #astype(int), astype(float)  #creates copy of array with given type!

array([23, 45,  1,  2,  3,  4,  5,  8,  9,  0])

In [48]:
arr2

array([23., 45.,  1.,  2.,  3.,  4.,  5.,  8.,  9.,  0.])

In [49]:
strArr = np.array(['4.5','5.2','4.0']) #Reading and converting values from Raw dataset 
strArr

array(['4.5', '5.2', '4.0'], dtype='<U3')

In [50]:
strArr1 = strArr.astype(float)
strArr1

array([4.5, 5.2, 4. ])

In [36]:
strArr2 = strArr1.astype(int)
strArr2

NameError: name 'strArr1' is not defined

<img src="elsp_0105.png" height="75%" width="75%"/>

### Explore 2 : Querying

In [52]:
xy = np.array([[1,23,45],[56,6,7],[78,34,25]])
xy

array([[ 1, 23, 45],
       [56,  6,  7],
       [78, 34, 25]])

In [53]:
[xy<40]

[array([[ True,  True, False],
        [False,  True,  True],
        [False,  True,  True]])]

In [54]:
xy[xy<40] #picking random array values!

array([ 1, 23,  6,  7, 34, 25])

In [55]:
xy[xy<10]

array([1, 6, 7])

In [56]:
xy[0]

array([ 1, 23, 45])

In [57]:
xy[0][1]

23

In [58]:
xy[1][xy[1]<40] #??

array([6, 7])

##   

## Airthmetic Operations

In [59]:
#Multiplying Arrays
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [60]:
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [61]:
#Addition
arr1+arr1

array([[ 2,  4,  6],
       [16, 18, 20]])

In [62]:
#Subtraction
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [63]:
#Arithmetic operations with scalars on array
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.125     , 0.11111111, 0.1       ]])

In [64]:
arr1/2

array([[0.5, 1. , 1.5],
       [4. , 4.5, 5. ]])

In [65]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]], dtype=int32)

In [66]:
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

#   

## Indexing & Slicing

In [146]:
#Creating sample array
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
#Get a value at an index
arr[8]

8

In [148]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [149]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [150]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [159]:
# Reset array, we'll see why i had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [161]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [162]:
# Now note the changes also occur in our original array!
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [163]:
# Data is not copied, it's a view of the original array! This avoids memory problems!
#To get a copy, need to be explicitly defined
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [164]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [165]:
arr_copy[0]=0
arr_copy

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [166]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [167]:
# Indexing a 2D array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [168]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [170]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[0][1]

10

In [171]:
# Getting individual element value
arr_2d[2,2]

45

In [172]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [81]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [180]:
arr_2d[:2,0]

array([ 5, 20])

In [179]:
#Shape bottom row
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [83]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [84]:
# Fancy Indexing

#Set up matrix
arr2d = np.zeros((10,10))
#Length of array
arr_length = arr2d.shape[1]
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [85]:
#Fancy indexing allows the following
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [86]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

#   

## Shapes and Transpose

In [183]:
#Create array
arr = np.arange(50).reshape((10,5))

#Show
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [184]:
#Lets transpose
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [185]:
arr.ravel() #convert to 1-D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [89]:
# Taking dot product of matrices
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [90]:
# For 3D matrix
arr3d = np.arange(50).reshape((5,5,2))

#Show
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [91]:
#We can also transpose a 3d matrix

arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [92]:
# If you need to get more specific use swapaxes
arr = np.array([[1,2,3]])

#Show 
arr

array([[1, 2, 3]])

In [93]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

#  

# Processing Array

In [94]:
#Lets learn how to use the numpy: where()

#First the slow way to do things

A = np.array([1,2,3,4])

B= np.array([100,200,300,400])

#Now a boolean array
condition = np.array([True,True,False,False])

#Using a list comprehension
answer = [(A_val if cond else B_val) for A_val,B_val,cond in zip(A,B,condition)]

#Show the answer
answer

#Problems include speed issues and multi-dimensional array issues

[1, 2, 300, 400]

In [95]:
#Now using numpy.where

answer2 = np.where(condition,A,B)

#Show
answer2

array([  1,   2, 300, 400])

In [96]:
#Can use np.where  on 2d for manipulation

from numpy.random import randn

arr = randn(3,4)

#Show arr
arr

array([[ 0.25736162,  1.58001695, -0.46939453,  0.39798964],
       [-0.23937175, -0.66805491, -0.21716438, -0.25333006],
       [-0.25063358, -0.06488662, -1.30671062, -0.40780818]])

In [97]:
# Where array is less than zero, make that value zero, otherwise leave it as the array value
np.where(arr < 0,1.0,arr/2)

array([[0.12868081, 0.79000848, 1.        , 0.19899482],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ]])

In [98]:
#Other Statistical Processing                  #statsmodel
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
#SUM
arr.sum()

45

In [100]:
#Can also do along an axis (we should expect a 3 diff between the columns)
arr.sum(0)

array([12, 15, 18])

In [101]:
arr.sum(1) #axis=1

array([ 6, 15, 24])

In [102]:
#Mean
arr.mean()

5.0

In [103]:
arr.mean(1) # ??

array([2., 5., 8.])

In [104]:
arr.mean(0)  # ??

array([4., 5., 6.])

In [105]:
#Standard Deviation
arr.std()

2.581988897471611

In [106]:
#Variance
arr.var()

6.666666666666667

In [107]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [108]:
np.square(arr)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [109]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
np.cumsum(arr) #random

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [112]:
np.cumprod(arr) #random

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [110]:
np.exp(arr) #Eulers - Exponential

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [120]:
#Also any and all for processing boolean arrays

bool_arr = np.array([True,False,False])

#For any True
bool_arr.any()

True

In [121]:
# For all True
bool_arr.all()

False

In [ ]:
(arr > 0).sum() #??

In [ ]:
(arr < 0).sum() #??

In [ ]:
#Sort it
arr.sort()
arr

In [123]:
#Lets learn about unique
countries = np.array(['France', 'Germany', 'USA', 'Russia','USA','Mexico','Germany'])
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')

In [ ]:
# in1d test values in one array
np.in1d(['France','USA','Sweden'],countries)

In [124]:
values=np.array([[1,2,3,4],[4,5,2,3]])
values

array([[1, 2, 3, 4],
       [4, 5, 2, 3]])

In [125]:
np.unique(values)

array([1, 2, 3, 4, 5])

In [126]:
values

array([[1, 2, 3, 4],
       [4, 5, 2, 3]])

In [127]:
np.in1d([2,3],values) #value checking #Task: change dim and test!

array([ True,  True])

In [128]:
np.in1d([12,34,56,30],values)

array([False, False, False, False])

In [134]:
np.isin([2,3,10],values)

array([ True,  True, False])

In [132]:
values

array([[1, 2, 3, 4],
       [4, 5, 2, 3]])

In [135]:
#repeat , tile
arr=np.arange(3)
arr

array([0, 1, 2])

In [137]:
np.tile(arr,3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [145]:
#arr.tile(3)

In [141]:
arr.repeat(3) #array -> repeat()

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [142]:
np.repeat(arr,3)  #np.repeat()

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [143]:
arr

array([0, 1, 2])

# Plot...

In [ ]:
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#Set array for one side of grid
points = np.arange(-5,5,0.01)

In [ ]:
#Create the grid
dx,dy=np.meshgrid(points,points)

In [ ]:
#Show what one side looks like
dx

In [ ]:
# Evaluating Function
z = (np.sin(dx) + np.sin(dy))

#Lets take a look at the z result
z

In [ ]:
#Plot out the 2d array
plt.imshow(z)

#Plot with a colorbar
plt.colorbar()

#Give the plot a title
plt.title("Plot for sin(x)+sin(y)")